# -*- coding: utf-8 -*-
"""Busit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/188NBTDdohpVsspjiHipZH-gYjT1--RM6
"""

import requests
import pandas as pd
from bs4 import BeautifulSoup
from datetime import datetime

url = "https://books.toscrape.com/"
response = requests.get(url, timeout=20)
soup = BeautifulSoup(response.text, "html.parser")
scrape_time = datetime.now().isoformat()

rows = []

for book in soup.select(".product_pod"):
    title = book.select_one("h3 a")["title"]
    price_text = book.select_one(".price_color").get_text(strip=True)
    availability = book.select_one(".availability").get_text(" ", strip=True)  # new field

    # The rating is stored as a CSS class, e.g. class="star-rating Three"
    # We grab the <p> element, then read its class list to find the rating word
    rating_paragraph = book.select_one("p.star-rating")  # new field
    rating = None
    if rating_paragraph:
        classes = rating_paragraph.get("class", [])           # e.g. ["star-rating", "Three"]
        rating = next((c for c in classes if c != "star-rating"), None)  # keep "Three"

    rows.append({
        "title": title,
        "price_text": price_text,
        "availability": availability,  # new field
        "rating": rating,              # new field
        "scraped_at": scrape_time,
    })

df = pd.DataFrame(rows)
df

# Check what your DataFrame looks like right now
print(f"Columns: {list(df.columns)}")
print(f"Data types:\n{df.dtypes}")
print(f"\nFirst 3 rows:")

# Remove the £ symbol and convert to a decimal number
df["price"] = (
    df["price_text"]
      .str.replace("Â£", "", regex=False)   # "£51.77" → "51.77"
      .astype(float)                        # "51.77" → 51.77
)

df

# See how many missing values exist per column
print(df.isnull().sum())

# Fill missing ratings with "Unknown" so they still appear in charts
df["rating"] = df["rating"].fillna("Unknown")

df = df.rename(columns={
    "price_text": "price_raw",     # original scraped string
    "price": "price_eur",          # cleaned numeric price
    "rating": "star_rating"        # clarify what kind of rating
})

print(df.columns.tolist())   # verify the renamed columns
df

# Final check
print(f"Rows: {len(df)}")
print(f"Columns: {list(df.columns)}")
print(f"Data types:\n{df.dtypes}")
print(f"\nSample:")


df.to_csv("verify_output.csv", index=False)
print(f"Rows: {len(df)}  |  Columns: {list(df.columns)}")


# How many rows and columns?
print(df.shape)

# Are there missing values?
print(df.isnull().sum())

# Does the data look right?
print(df.describe())   # numeric summary
  # first few rows

# Add a price tier for dashboard grouping
df["price_tier"] = df["price_eur"].apply(
    lambda p: "Budget" if p < 20
    else ("Mid-range" if p < 40 else "Premium")
)

df[["title", "price_eur", "price_tier"]].head(5)

# Convert "One", "Two", ... to 1, 2, ...
rating_map = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}
df["rating_numeric"] = df["star_rating"].map(rating_map)

df[["title", "star_rating", "rating_numeric"]].head(5)

# True if the book is in stock
df["in_stock"] = df["availability"].str.contains("In stock", na=False)

df["in_stock"].value_counts()

# Example: drop the raw price string (you already have price_eur)
df = df.drop(columns=["price_raw"], errors="ignore")

from supabase import create_client
from datetime import datetime

import os

SUPABASE_URL = os.environ["SUPABASE_URL"]
SUPABASE_KEY = os.environ["SUPABASE_KEY"]

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

scrape_time = datetime.now().isoformat()

rows = []
for _, row in df.iterrows():
    rows.append({
        "title":        str(row.get("title", "")),
        "price_eur":    float(row.get("price_eur", 0)),
        "star_rating":  str(row.get("star_rating", "")),
        "availability": str(row.get("availability", "")),
        "scraped_at":   scrape_time,
    })

result = supabase.table("books").insert(rows).execute()
print(f"✅ Inserted {len(rows)} rows into Supabase")